version: 2

sources:
  - name: airbnb
    schema: raw
    tables:
      - name: listings
        description: Raw loaded table containing Airbnb listings.
        identifier: raw_listings

      - name: hosts
        description: Raw loaded table containing Airbnb hosts.
        identifier: raw_hosts

      - name: reviews
        description: Raw loaded table containing Airbnb reviews.
        identifier: raw_reviews
        loaded_at_field: date
        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 48, period: hour}